### ISSUE TITLE
Where are the images saved?

### ISSUE THREAD

**Issue by KD4PYR** [NCAR/pi-wrf#6]
Running the latest version and love that my students could save the text/images from the run. 

Planning on having them build a PI, and then run the model and share the output while studying from home. 

I just can not figure out where the run information is being saved, so I can include instructions for copying and sharing the files.

Thanks.

**Comment by wefoust** [comment]
Hi KD4PYR, 
We've noticed a bug in this as it was pushed, and we are working on a patch for it now. We'll also update instructions that will show users how to mount a volume so it saves to present working directory. ETA is within a week.

**Comment by wefoust** [comment]
Hi KD4PYR,
I would like to swing back to this. An updated was pushed some time ago that fixed the file save. The easiest way to now use it is to run the app with the following command (all one line or use "\" for line continuation). The files should be saved in your present working directory. 

sudo docker run -it --rm --net=host -e "DISPLAY" -v $(pwd):/pi-wrf/Output/user_saved_files -v $HOME/.Xauthority:/root/.Xauthority ncar/pi-wrf

**Comment by KD4PYR** [comment]
Thanks. This is a much better way. I have been running the sudo docker cp <container id>/pi-wrf/Output /Downloads/ to save the output from the new release.
